# Site settings
title: Jared H. Taylor
description: Musician, Actor, FemBoy # this means to ignore newlines until "baseurl:"
baseurl: "/" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site
author: Copyright &copy; 2020 - Jared H. Taylor
lang: en_US

# Build settings
safe: true # always trues on github-pages, disables _plugins/
markdown: kramdown
sass:
  indentWidth: 4
  style: compressed
  precision: 10
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
exclude:
  - .gitignore
  - Gemfile
  - Gemfile.lock
  - build-in-docker.sh
  - README.md
